version: '3'
services:
  drupal:
    image: drupal:latest
    ports:
      - "80:80"
    networks:
      - drupal
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
  postgres:
    image: postgres:latest
    networks:
      - drupal
    environment:
      - POSTGRES_USER=drupal
      - POSTGRES_PASSWORD=drupal
      - POSTGRES_DB=drupal
networks:
  drupal:
    driver: bridge

